### ISSUE TITLE
/usr/bin/ld: cannot find -lmarkdown

### ISSUE THREAD

**Issue by lf-araujo** [h3rald/hastyscribe#70]
Hi, 

thanks for this!

I am facing some missing library on my system. The command

`nim c -d:release -d:discount src/hastyscribe.nim`

Generates the error

`/usr/bin/ld: cannot find -lmarkdown`

I am running it in a debian based distribution, which library I should be missing?

**Comment by h3rald** [comment]
Hey!

Right, I tried myself and yes, I can reproduce it... BUT hopefully it's a silly thing. I updated the README instruction for building HastyScribe from source to clarify that you have to go to the **src** directory before building it, otherwise it won't pick up the markdown library.

So:

1. Download and install [Nim][nim].
2. Download and build [Nifty][nifty], and put it somewhere in your $PATH.
3. Clone the HastyScribe [repository](https://github.com/h3rald/hastyscribe).
4. Navigate to the HastyScribe repository local folder.
5. Run **nifty install** to download HastyScribe's dependencies.
6. Run **nifty build discount** to build the Discount markdown library.
7. Go to the **src** folder and run **nim c -d:release -d:discount hastyscribe.nim**

...Assuming you did everything else, in particular step 5 and 6, which are necessary to build the discount markdown library from source.

**Comment by lf-araujo** [comment]
Thank you,

this solved the issue.

Best,
lf
